
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-user-db
    environment:
      - ORACLE_PASSWORD=Oracle123
      - APP_USER=userservice
      - APP_USER_PASSWORD=userservice123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - user-service-network

  user-management-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: user-management-service
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=userservice
      - SPRING_DATASOURCE_PASSWORD=userservice123
    networks:
      - user-service-network
    restart: unless-stopped


volumes:
  oracle_data:

networks:
  user-service-network:
    driver: bridge